# cmake/BootstrapVcpkg.cmake
cmake_minimum_required(VERSION 3.20)

# --- VCPKG root meghatározása ---
if(NOT DEFINED VCPKG_ROOT)
    if(DEFINED ENV{VCPKG_ROOT})
        file(TO_CMAKE_PATH "$ENV{VCPKG_ROOT}" VCPKG_ROOT)
    elseif(WIN32)
        set(VCPKG_ROOT "C:/vcpkg")
    else()
        set(VCPKG_ROOT "${CMAKE_SOURCE_DIR}/vcpkg")
    endif()
endif()

# --- Clone, ha még nincs ---
if(NOT EXISTS "${VCPKG_ROOT}")
    message(STATUS "Cloning vcpkg into ${VCPKG_ROOT}")
    execute_process(
        COMMAND git clone https://github.com/microsoft/vcpkg.git "${VCPKG_ROOT}"
        RESULT_VARIABLE result
    )
    if(result)
        message(FATAL_ERROR "Failed to clone vcpkg")
    endif()
endif()

# --- Bootstrap, ha nincs bináris ---
if(WIN32)
    set(_vcpkg_exe "${VCPKG_ROOT}/vcpkg.exe")
else()
    set(_vcpkg_exe "${VCPKG_ROOT}/vcpkg")
endif()

if(NOT EXISTS "${_vcpkg_exe}")
    message(STATUS "Bootstrapping vcpkg...")
    if(WIN32)
        execute_process(
            COMMAND cmd /c bootstrap-vcpkg.bat -disableMetrics
            WORKING_DIRECTORY ${VCPKG_ROOT}
            RESULT_VARIABLE result
        )
    else()
        execute_process(
            COMMAND ./bootstrap-vcpkg.sh -disableMetrics
            WORKING_DIRECTORY ${VCPKG_ROOT}
            RESULT_VARIABLE result
        )
    endif()
    if(result)
        message(FATAL_ERROR "Failed to bootstrap vcpkg")
    endif()
endif()

# --- vcpkg integrate install ---
# Ez rakja le a %LOCALAPPDATA%\vcpkg\vcpkg.user.targets fájlt,
# ami nélkül a Visual Studio "Use Vcpkg = No"-t mutat!
if(WIN32 AND NOT DEFINED VCPKG_INTEGRATED)
    message(STATUS "Running vcpkg integrate install...")
    execute_process(
        COMMAND "${_vcpkg_exe}" integrate install
        WORKING_DIRECTORY ${VCPKG_ROOT}
        RESULT_VARIABLE res
        OUTPUT_VARIABLE integrate_out
    )
    if(NOT res EQUAL 0)
        message(WARNING "vcpkg integrate install failed – futtasd manuálisan: ${_vcpkg_exe} integrate install")
    else()
        set(VCPKG_INTEGRATED TRUE CACHE INTERNAL "vcpkg integrated")
        message(STATUS "vcpkg integrate install: OK")
    endif()
endif()

# --- Toolchain ---
# CACHE STRING (FORCE nelkul): ha mar benn van a cache-ben (masodik
# configure futaskor), nem irja felul. Elso futasra bekerül a cache-be,
# masodik futasra a CMake mar a cache-bol olvassa project() elott.
# Ez az eredeti, mukodo mechanizmus.
if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    set(CMAKE_TOOLCHAIN_FILE
        "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
        CACHE STRING "Vcpkg toolchain file"
    )
endif()
message(STATUS "vcpkg toolchain: ${CMAKE_TOOLCHAIN_FILE}")

# --- Triplet ---
if(NOT DEFINED VCPKG_TARGET_TRIPLET)
    if(WIN32)
        if(VCPKG_TRIPLET_TYPE STREQUAL "dynamic")
            set(VCPKG_TARGET_TRIPLET "x64-windows"        CACHE STRING "vcpkg triplet" FORCE)
        else()
            set(VCPKG_TARGET_TRIPLET "x64-windows-static" CACHE STRING "vcpkg triplet" FORCE)
        endif()
    elseif(APPLE)
        set(VCPKG_TARGET_TRIPLET "x64-osx"   CACHE STRING "vcpkg triplet")
    elseif(UNIX)
        set(VCPKG_TARGET_TRIPLET "x64-linux" CACHE STRING "vcpkg triplet")
    endif()
endif()

if(NOT DEFINED VCPKG_HOST_TRIPLET)
    set(VCPKG_HOST_TRIPLET "${VCPKG_TARGET_TRIPLET}" CACHE STRING "vcpkg host triplet")
endif()

message(STATUS "vcpkg root:    ${VCPKG_ROOT}")
message(STATUS "vcpkg triplet: ${VCPKG_TARGET_TRIPLET}")
message(STATUS "vcpkg toolchain: ${CMAKE_TOOLCHAIN_FILE}")

# ---------------------------------------------------------------
# Directory.Build.props generálása
#
# A Visual Studio "Use Vcpkg" property page értéke NEM a CMake
# VS globals-ból jön, hanem az MSBuild property rendszerből.
# Az egyetlen megbízható módja, hogy minden .vcxproj-ban "Yes"
# legyen: egy Directory.Build.props fájl a build root-ban,
# amit az MSBuild automatikusan importál minden projekthez.
# ---------------------------------------------------------------
if(WIN32 AND CMAKE_GENERATOR MATCHES "Visual Studio")
    if(VCPKG_TRIPLET_TYPE STREQUAL "dynamic")
        set(_vcpkg_use_static "false")
        set(_vcpkg_triplet    "x64-windows")
    else()
        set(_vcpkg_use_static "true")
        set(_vcpkg_triplet    "x64-windows-static")
    endif()

    if(VCPKG_TRIPLET_TYPE STREQUAL "static")
        # /MT  = Release statikus CRT
        # /MTd = Debug statikus CRT
        set(_rt_release "MultiThreaded")
        set(_rt_debug   "MultiThreadedDebug")
    else()
        # /MD  = Release DLL CRT
        # /Mdd = Debug DLL CRT
        set(_rt_release "MultiThreadedDLL")
        set(_rt_debug   "MultiThreadedDebugDLL")
    endif()

    set(_props_output "${CMAKE_BINARY_DIR}/Directory.Build.props")

    # string(CONFIGURE) + file(WRITE) kombináció:
    # A @VAR@ helyeken a CMake valtozo ertekek lesznek behelyettesitve,
    # majd a mar kesz XML stringet irjuk ki - igy biztosan valid UTF-8 lesz.
    string(CONFIGURE [[
<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated by CMake - do not edit manually -->
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VcpkgEnabled>true</VcpkgEnabled>
    <VcpkgTriplet>@_vcpkg_triplet@</VcpkgTriplet>
    <VcpkgHostTriplet>@_vcpkg_triplet@</VcpkgHostTriplet>
    <VcpkgUseStatic>@_vcpkg_use_static@</VcpkgUseStatic>
    <VcpkgConfiguration>$(Configuration)</VcpkgConfiguration>
    <VcpkgEnableManifest>false</VcpkgEnableManifest>
    <VcpkgRoot>@VCPKG_ROOT@</VcpkgRoot>
  </PropertyGroup>

  <!-- Security hardening - all projects -->
  <ItemDefinitionGroup>
    <ClCompile>
      <BufferSecurityCheck>true</BufferSecurityCheck>
      <SDLCheck>true</SDLCheck>
      <SpectreMitigation>Spectre</SpectreMitigation>
      <ControlFlowGuard Condition="'@ENABLE_ASAN@'!='ON'">Guard</ControlFlowGuard>
      <ControlFlowGuard Condition="'@ENABLE_ASAN@'=='ON'">false</ControlFlowGuard>
    </ClCompile>
    <Link>
      <DataExecutionPrevention>true</DataExecutionPrevention>
      <RandomizedBaseAddress>true</RandomizedBaseAddress>
      <HighEntropyVA>true</HighEntropyVA>
      <ImageHasSafeExceptionHandlers Condition="'$(Platform)'=='Win32'">true</ImageHasSafeExceptionHandlers>
    </Link>
  </ItemDefinitionGroup>

  <!-- RTC1: Debug only, not with ASAN -->
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug' And '@ENABLE_ASAN@'!='ON'">
    <ClCompile>
      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>
    </ClCompile>
  </ItemDefinitionGroup>

  <!-- RuntimeLibrary + LTCG: normal build -->
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release' And '@ENABLE_ASAN@'!='ON'">
    <ClCompile><RuntimeLibrary>@_rt_release@</RuntimeLibrary></ClCompile>
    <Link><LinkTimeCodeGeneration>UseFastLinkTimeCodeGeneration</LinkTimeCodeGeneration></Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug' And '@ENABLE_ASAN@'!='ON'">
    <ClCompile><RuntimeLibrary>@_rt_debug@</RuntimeLibrary></ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='RelWithDebInfo' And '@ENABLE_ASAN@'!='ON'">
    <ClCompile><RuntimeLibrary>@_rt_release@</RuntimeLibrary></ClCompile>
    <Link><LinkTimeCodeGeneration>UseFastLinkTimeCodeGeneration</LinkTimeCodeGeneration></Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='MinSizeRel' And '@ENABLE_ASAN@'!='ON'">
    <ClCompile><RuntimeLibrary>@_rt_release@</RuntimeLibrary></ClCompile>
    <Link><LinkTimeCodeGeneration>UseFastLinkTimeCodeGeneration</LinkTimeCodeGeneration></Link>
  </ItemDefinitionGroup>

  <!-- RuntimeLibrary: ASAN build - DLL CRT required, no LTCG -->
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release' And '@ENABLE_ASAN@'=='ON'">
    <ClCompile><RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary></ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug' And '@ENABLE_ASAN@'=='ON'">
    <ClCompile><RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary></ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='RelWithDebInfo' And '@ENABLE_ASAN@'=='ON'">
    <ClCompile><RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary></ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)'=='MinSizeRel' And '@ENABLE_ASAN@'=='ON'">
    <ClCompile><RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary></ClCompile>
  </ItemDefinitionGroup>

</Project>
]] _props_content @ONLY)

    file(WRITE "${_props_output}" "${_props_content}")
    message(STATUS "Directory.Build.props written: ${_props_output}")
    # A fájl a CMAKE_BINARY_DIR-be kerül (ahol a .sln is van),
    # az MSBuild automatikusan megtalálja.
    file(WRITE "${CMAKE_BINARY_DIR}/Directory.Build.props" "${_props_content}")
    message(STATUS "Directory.Build.props generálva: ${CMAKE_BINARY_DIR}/Directory.Build.props")
endif()

# --- vcpkg_require() ---
function(vcpkg_require)
    foreach(PACKAGE IN LISTS ARGN)
        string(TOLOWER "${PACKAGE}" PACKAGE_LOWER)
        find_package(${PACKAGE} QUIET)
        if(NOT ${PACKAGE}_FOUND)
            message(STATUS "vcpkg install: ${PACKAGE_LOWER}:${VCPKG_TARGET_TRIPLET}")
            execute_process(
                COMMAND "${_vcpkg_exe}" install "${PACKAGE_LOWER}:${VCPKG_TARGET_TRIPLET}"
                RESULT_VARIABLE result
            )
            if(result)
                message(FATAL_ERROR "vcpkg: Nem sikerült telepíteni: ${PACKAGE_LOWER}")
            endif()
        endif()
    endforeach()
endfunction()
